- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: test cluster
      shell: kubectl get nodes >> k8s-cluster-info.log
      args:
        chdir: /home/ubuntu
        creates: k8s-cluster-info.log