- hosts: master
  become: yes
  tasks:
    - name: enable docker service
      service: 
         name: docker.service
         enabled: yes 
      
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors all >> cluster_initialized.txt
      args:
        chdir: /home/ubuntu
        creates: cluster_initialized.txt
    
    - name: set KUBECONFIG
      shell: export KUBECONFIG=/etc/kubernetes/admin.conf && echo "export KUBECONFIG=/etc/kubernetes/admin.conf" >> kubeconfig.log
      args:
        chdir: /home/ubuntu
        creates: kubeconfig.log

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: install Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.log
      args:
        chdir: /home/ubuntu
        creates: pod_network_setup.log